server:
  port: 8081

spring:
  application:
    name: config-api
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/Trilha_N2
    username: postgres
    password: dev92
  jpa:
    hibernate:
      ddl-auto: validate           # você já criou as tabelas; só valida
    properties:
      hibernate.format_sql: true
  data:
    redis:
      host: localhost              # se a API usa Redis para o GET rápido
      port: 6379

# suas propriedades customizadas (lidas pela SecurityConfig e Producer)
app:
  kafka:
    topic: config.events
  security:
    user: admin
    password: admin123

# Swagger / OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Actuator / Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name:unknown}
