server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:postgresql://localhost:5432/Trilha_N2   # ajuste a porta se usou 5433
    username: postgres
    password: dev92

  jpa:
    hibernate:
      ddl-auto: validate        # você já criou as tabelas; só valide
    properties:
      hibernate.format_sql: true

app:
  kafka:
    topic: config.events
  security:
    user: admin
    password: admin123
