server:
  port: 8082

config:
  sdk:
    namespace: billing
    env: dev
    bootstrap-servers: localhost:9092
    topic: config.events
    api-base-url: http://localhost:8081
    api-username: admin
    api-password: admin123
